version: '3.8'
services:
  flutter:
    build: .
    container_name: docker-flutter
    privileged: true
    volumes:
      - ./workspace:/home/developer/workspace
      - /dev/bus/usb:/dev/bus/usb # Use only in linux distros
    command: tail -f /dev/null