version: '3'

services:
  flutter_docker:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    image: flutter_docker_img
    container_name: flutter_docker_container
    privileged: true
    volumes:
      - ../workspace:/home/developer/workspace
    networks:
      - flutter_docker_network

networks:
  flutter_docker_network:
    driver: host

