version: '3.8'
services:
  flutter:
    build: .
    container_name: docker-flutter
    privileged: true
    volumes:
      - ./workspace:/var/www/html
      - /dev/bus/usb:/dev/bus/usb # Use only in linux distros
    ports:
      - 8087:80
    command: tail -f /dev/null